builds:
  - binary: kafka-kinesis
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
archive:
  name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
  format: binary
  replacements:
    darwin: mac
