language: go
go:
- 1.9
sudo: false
after_success:
  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash
env:
  global:
    - secure: "aE6cEchxVejNjyCBLD+S44wFDT0rA1A24YA/vG8t729ZS7TbfFnrxq4XQZqgJ41TEhxBURSd8BTks3fFSee8IByVrIrOUQNm7nEgnWs6KJ3uurZKyKzEPKx8kFZ/T/+rxtLb2jxq4dN8MqHA4WQfXtRnvCfN2TS8wirHxdi2iiBN1vnW7NCfzkcEjN5qQtTczCOG/nqtVH6A+cv1EByCrmtcJ8a3CiXZeB+nHjZ508gwreKDGIbX3bFQqLi82gJpE81FNrsB59PintHnggO2c+T4jfsSLm5hOUe9IhThmNbierx56EiwD32dNttAwp9sDC6wg4dW74k+VeUn7hZtV7nXg94w7UZDajSlrnBn51jcOttP15PLe7GNFBtUUE3wljbt6b7f740Squh61XLamzzn+qSEdrNDO8b1To2myHb3ZemhqXzYQfPfYa0F5qaKdPReepN8IgoTv8xDZ8N63VzTHSUvc3RBwmeVOWlTQuDwTRbGXEYEqgfWF6iCsV4Tgl5IPkKb+ZeS7AhLT7XsS45udtVi2QztmiTIXvUgYfB4BIkhepsYHwDuR4ZI7XQ/CoX2svQEBaC/uV4vR3O2DMmWaj5ymRHUrN7lfTdcgA6yIh8TIgaPMqsS98VMjHqUHJK43WDsfsh3s8nsptwdd3WrsH32eLZHTUJBKEzDYh4="
